package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;
import java.util.Date;

public class Aquaculture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.name
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id_fowlery
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idFowlery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idPatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.num_total
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Integer numTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.feed_type
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String feedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.feed_weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Float feedWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id_recorder
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idRecorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.id_outstorage
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idOutstorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquaculture.weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id
     *
     * @return the value of aquaculture.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id
     *
     * @param id the value for aquaculture.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.name
     *
     * @return the value of aquaculture.name
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.name
     *
     * @param name the value for aquaculture.name
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id_fowlery
     *
     * @return the value of aquaculture.id_fowlery
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdFowlery() {
        return idFowlery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id_fowlery
     *
     * @param idFowlery the value for aquaculture.id_fowlery
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdFowlery(String idFowlery) {
        this.idFowlery = idFowlery == null ? null : idFowlery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id_patch
     *
     * @return the value of aquaculture.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdPatch() {
        return idPatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id_patch
     *
     * @param idPatch the value for aquaculture.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdPatch(String idPatch) {
        this.idPatch = idPatch == null ? null : idPatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.record_date
     *
     * @return the value of aquaculture.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.record_date
     *
     * @param recordDate the value for aquaculture.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.num_total
     *
     * @return the value of aquaculture.num_total
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Integer getNumTotal() {
        return numTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.num_total
     *
     * @param numTotal the value for aquaculture.num_total
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setNumTotal(Integer numTotal) {
        this.numTotal = numTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.feed_type
     *
     * @return the value of aquaculture.feed_type
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getFeedType() {
        return feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.feed_type
     *
     * @param feedType the value for aquaculture.feed_type
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setFeedType(String feedType) {
        this.feedType = feedType == null ? null : feedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.feed_weight
     *
     * @return the value of aquaculture.feed_weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Float getFeedWeight() {
        return feedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.feed_weight
     *
     * @param feedWeight the value for aquaculture.feed_weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setFeedWeight(Float feedWeight) {
        this.feedWeight = feedWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.remark
     *
     * @return the value of aquaculture.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.remark
     *
     * @param remark the value for aquaculture.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id_recorder
     *
     * @return the value of aquaculture.id_recorder
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdRecorder() {
        return idRecorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id_recorder
     *
     * @param idRecorder the value for aquaculture.id_recorder
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdRecorder(String idRecorder) {
        this.idRecorder = idRecorder == null ? null : idRecorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id_charge
     *
     * @return the value of aquaculture.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdCharge() {
        return idCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id_charge
     *
     * @param idCharge the value for aquaculture.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdCharge(String idCharge) {
        this.idCharge = idCharge == null ? null : idCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.id_outstorage
     *
     * @return the value of aquaculture.id_outstorage
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdOutstorage() {
        return idOutstorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.id_outstorage
     *
     * @param idOutstorage the value for aquaculture.id_outstorage
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdOutstorage(String idOutstorage) {
        this.idOutstorage = idOutstorage == null ? null : idOutstorage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.status
     *
     * @return the value of aquaculture.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.status
     *
     * @param status the value for aquaculture.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquaculture.weight
     *
     * @return the value of aquaculture.weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquaculture.weight
     *
     * @param weight the value for aquaculture.weight
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", idFowlery=").append(idFowlery);
        sb.append(", idPatch=").append(idPatch);
        sb.append(", recordDate=").append(recordDate);
        sb.append(", numTotal=").append(numTotal);
        sb.append(", feedType=").append(feedType);
        sb.append(", feedWeight=").append(feedWeight);
        sb.append(", remark=").append(remark);
        sb.append(", idRecorder=").append(idRecorder);
        sb.append(", idCharge=").append(idCharge);
        sb.append(", idOutstorage=").append(idOutstorage);
        sb.append(", status=").append(status);
        sb.append(", weight=").append(weight);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}