package cn.zhku.waterfowl.pojo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AquacultureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public AquacultureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdFowleryIsNull() {
            addCriterion("id_fowlery is null");
            return (Criteria) this;
        }

        public Criteria andIdFowleryIsNotNull() {
            addCriterion("id_fowlery is not null");
            return (Criteria) this;
        }

        public Criteria andIdFowleryEqualTo(String value) {
            addCriterion("id_fowlery =", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryNotEqualTo(String value) {
            addCriterion("id_fowlery <>", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryGreaterThan(String value) {
            addCriterion("id_fowlery >", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryGreaterThanOrEqualTo(String value) {
            addCriterion("id_fowlery >=", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryLessThan(String value) {
            addCriterion("id_fowlery <", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryLessThanOrEqualTo(String value) {
            addCriterion("id_fowlery <=", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryLike(String value) {
            addCriterion("id_fowlery like", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryNotLike(String value) {
            addCriterion("id_fowlery not like", value, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryIn(List<String> values) {
            addCriterion("id_fowlery in", values, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryNotIn(List<String> values) {
            addCriterion("id_fowlery not in", values, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryBetween(String value1, String value2) {
            addCriterion("id_fowlery between", value1, value2, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdFowleryNotBetween(String value1, String value2) {
            addCriterion("id_fowlery not between", value1, value2, "idFowlery");
            return (Criteria) this;
        }

        public Criteria andIdPatchIsNull() {
            addCriterion("id_patch is null");
            return (Criteria) this;
        }

        public Criteria andIdPatchIsNotNull() {
            addCriterion("id_patch is not null");
            return (Criteria) this;
        }

        public Criteria andIdPatchEqualTo(String value) {
            addCriterion("id_patch =", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotEqualTo(String value) {
            addCriterion("id_patch <>", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchGreaterThan(String value) {
            addCriterion("id_patch >", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchGreaterThanOrEqualTo(String value) {
            addCriterion("id_patch >=", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLessThan(String value) {
            addCriterion("id_patch <", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLessThanOrEqualTo(String value) {
            addCriterion("id_patch <=", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLike(String value) {
            addCriterion("id_patch like", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotLike(String value) {
            addCriterion("id_patch not like", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchIn(List<String> values) {
            addCriterion("id_patch in", values, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotIn(List<String> values) {
            addCriterion("id_patch not in", values, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchBetween(String value1, String value2) {
            addCriterion("id_patch between", value1, value2, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotBetween(String value1, String value2) {
            addCriterion("id_patch not between", value1, value2, "idPatch");
            return (Criteria) this;
        }

        public Criteria andRecordDateIsNull() {
            addCriterion("record_date is null");
            return (Criteria) this;
        }

        public Criteria andRecordDateIsNotNull() {
            addCriterion("record_date is not null");
            return (Criteria) this;
        }

        public Criteria andRecordDateEqualTo(Date value) {
            addCriterion("record_date =", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotEqualTo(Date value) {
            addCriterion("record_date <>", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateGreaterThan(Date value) {
            addCriterion("record_date >", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateGreaterThanOrEqualTo(Date value) {
            addCriterion("record_date >=", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateLessThan(Date value) {
            addCriterion("record_date <", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateLessThanOrEqualTo(Date value) {
            addCriterion("record_date <=", value, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateIn(List<Date> values) {
            addCriterion("record_date in", values, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotIn(List<Date> values) {
            addCriterion("record_date not in", values, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateBetween(Date value1, Date value2) {
            addCriterion("record_date between", value1, value2, "recordDate");
            return (Criteria) this;
        }

        public Criteria andRecordDateNotBetween(Date value1, Date value2) {
            addCriterion("record_date not between", value1, value2, "recordDate");
            return (Criteria) this;
        }

        public Criteria andNumTotalIsNull() {
            addCriterion("num_total is null");
            return (Criteria) this;
        }

        public Criteria andNumTotalIsNotNull() {
            addCriterion("num_total is not null");
            return (Criteria) this;
        }

        public Criteria andNumTotalEqualTo(Integer value) {
            addCriterion("num_total =", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotEqualTo(Integer value) {
            addCriterion("num_total <>", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalGreaterThan(Integer value) {
            addCriterion("num_total >", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_total >=", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalLessThan(Integer value) {
            addCriterion("num_total <", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalLessThanOrEqualTo(Integer value) {
            addCriterion("num_total <=", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalIn(List<Integer> values) {
            addCriterion("num_total in", values, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotIn(List<Integer> values) {
            addCriterion("num_total not in", values, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalBetween(Integer value1, Integer value2) {
            addCriterion("num_total between", value1, value2, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("num_total not between", value1, value2, "numTotal");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIsNull() {
            addCriterion("feed_type is null");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIsNotNull() {
            addCriterion("feed_type is not null");
            return (Criteria) this;
        }

        public Criteria andFeedTypeEqualTo(String value) {
            addCriterion("feed_type =", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotEqualTo(String value) {
            addCriterion("feed_type <>", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeGreaterThan(String value) {
            addCriterion("feed_type >", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("feed_type >=", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLessThan(String value) {
            addCriterion("feed_type <", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLessThanOrEqualTo(String value) {
            addCriterion("feed_type <=", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLike(String value) {
            addCriterion("feed_type like", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotLike(String value) {
            addCriterion("feed_type not like", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIn(List<String> values) {
            addCriterion("feed_type in", values, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotIn(List<String> values) {
            addCriterion("feed_type not in", values, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeBetween(String value1, String value2) {
            addCriterion("feed_type between", value1, value2, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotBetween(String value1, String value2) {
            addCriterion("feed_type not between", value1, value2, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedWeightIsNull() {
            addCriterion("feed_weight is null");
            return (Criteria) this;
        }

        public Criteria andFeedWeightIsNotNull() {
            addCriterion("feed_weight is not null");
            return (Criteria) this;
        }

        public Criteria andFeedWeightEqualTo(Float value) {
            addCriterion("feed_weight =", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightNotEqualTo(Float value) {
            addCriterion("feed_weight <>", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightGreaterThan(Float value) {
            addCriterion("feed_weight >", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("feed_weight >=", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightLessThan(Float value) {
            addCriterion("feed_weight <", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightLessThanOrEqualTo(Float value) {
            addCriterion("feed_weight <=", value, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightIn(List<Float> values) {
            addCriterion("feed_weight in", values, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightNotIn(List<Float> values) {
            addCriterion("feed_weight not in", values, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightBetween(Float value1, Float value2) {
            addCriterion("feed_weight between", value1, value2, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andFeedWeightNotBetween(Float value1, Float value2) {
            addCriterion("feed_weight not between", value1, value2, "feedWeight");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIsNull() {
            addCriterion("id_recorder is null");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIsNotNull() {
            addCriterion("id_recorder is not null");
            return (Criteria) this;
        }

        public Criteria andIdRecorderEqualTo(String value) {
            addCriterion("id_recorder =", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotEqualTo(String value) {
            addCriterion("id_recorder <>", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderGreaterThan(String value) {
            addCriterion("id_recorder >", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderGreaterThanOrEqualTo(String value) {
            addCriterion("id_recorder >=", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLessThan(String value) {
            addCriterion("id_recorder <", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLessThanOrEqualTo(String value) {
            addCriterion("id_recorder <=", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLike(String value) {
            addCriterion("id_recorder like", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotLike(String value) {
            addCriterion("id_recorder not like", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIn(List<String> values) {
            addCriterion("id_recorder in", values, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotIn(List<String> values) {
            addCriterion("id_recorder not in", values, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderBetween(String value1, String value2) {
            addCriterion("id_recorder between", value1, value2, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotBetween(String value1, String value2) {
            addCriterion("id_recorder not between", value1, value2, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdChargeIsNull() {
            addCriterion("id_charge is null");
            return (Criteria) this;
        }

        public Criteria andIdChargeIsNotNull() {
            addCriterion("id_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIdChargeEqualTo(String value) {
            addCriterion("id_charge =", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotEqualTo(String value) {
            addCriterion("id_charge <>", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeGreaterThan(String value) {
            addCriterion("id_charge >", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeGreaterThanOrEqualTo(String value) {
            addCriterion("id_charge >=", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLessThan(String value) {
            addCriterion("id_charge <", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLessThanOrEqualTo(String value) {
            addCriterion("id_charge <=", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLike(String value) {
            addCriterion("id_charge like", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotLike(String value) {
            addCriterion("id_charge not like", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeIn(List<String> values) {
            addCriterion("id_charge in", values, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotIn(List<String> values) {
            addCriterion("id_charge not in", values, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeBetween(String value1, String value2) {
            addCriterion("id_charge between", value1, value2, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotBetween(String value1, String value2) {
            addCriterion("id_charge not between", value1, value2, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageIsNull() {
            addCriterion("id_outstorage is null");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageIsNotNull() {
            addCriterion("id_outstorage is not null");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageEqualTo(String value) {
            addCriterion("id_outstorage =", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageNotEqualTo(String value) {
            addCriterion("id_outstorage <>", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageGreaterThan(String value) {
            addCriterion("id_outstorage >", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageGreaterThanOrEqualTo(String value) {
            addCriterion("id_outstorage >=", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageLessThan(String value) {
            addCriterion("id_outstorage <", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageLessThanOrEqualTo(String value) {
            addCriterion("id_outstorage <=", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageLike(String value) {
            addCriterion("id_outstorage like", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageNotLike(String value) {
            addCriterion("id_outstorage not like", value, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageIn(List<String> values) {
            addCriterion("id_outstorage in", values, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageNotIn(List<String> values) {
            addCriterion("id_outstorage not in", values, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageBetween(String value1, String value2) {
            addCriterion("id_outstorage between", value1, value2, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andIdOutstorageNotBetween(String value1, String value2) {
            addCriterion("id_outstorage not between", value1, value2, "idOutstorage");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Float value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Float value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Float value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Float value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Float value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Float> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Float> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Float value1, Float value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Float value1, Float value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aquaculture
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 04 21:51:04 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aquaculture
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}