package cn.zhku.waterfowl.pojo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EpidemicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public EpidemicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFowleryIdIsNull() {
            addCriterion("fowlery_id is null");
            return (Criteria) this;
        }

        public Criteria andFowleryIdIsNotNull() {
            addCriterion("fowlery_id is not null");
            return (Criteria) this;
        }

        public Criteria andFowleryIdEqualTo(String value) {
            addCriterion("fowlery_id =", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdNotEqualTo(String value) {
            addCriterion("fowlery_id <>", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdGreaterThan(String value) {
            addCriterion("fowlery_id >", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdGreaterThanOrEqualTo(String value) {
            addCriterion("fowlery_id >=", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdLessThan(String value) {
            addCriterion("fowlery_id <", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdLessThanOrEqualTo(String value) {
            addCriterion("fowlery_id <=", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdLike(String value) {
            addCriterion("fowlery_id like", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdNotLike(String value) {
            addCriterion("fowlery_id not like", value, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdIn(List<String> values) {
            addCriterion("fowlery_id in", values, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdNotIn(List<String> values) {
            addCriterion("fowlery_id not in", values, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdBetween(String value1, String value2) {
            addCriterion("fowlery_id between", value1, value2, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andFowleryIdNotBetween(String value1, String value2) {
            addCriterion("fowlery_id not between", value1, value2, "fowleryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdIsNull() {
            addCriterion("inventory_id is null");
            return (Criteria) this;
        }

        public Criteria andInventoryIdIsNotNull() {
            addCriterion("inventory_id is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryIdEqualTo(String value) {
            addCriterion("inventory_id =", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotEqualTo(String value) {
            addCriterion("inventory_id <>", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdGreaterThan(String value) {
            addCriterion("inventory_id >", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("inventory_id >=", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdLessThan(String value) {
            addCriterion("inventory_id <", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdLessThanOrEqualTo(String value) {
            addCriterion("inventory_id <=", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdLike(String value) {
            addCriterion("inventory_id like", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotLike(String value) {
            addCriterion("inventory_id not like", value, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdIn(List<String> values) {
            addCriterion("inventory_id in", values, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotIn(List<String> values) {
            addCriterion("inventory_id not in", values, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdBetween(String value1, String value2) {
            addCriterion("inventory_id between", value1, value2, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryIdNotBetween(String value1, String value2) {
            addCriterion("inventory_id not between", value1, value2, "inventoryId");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andDiseaesIsNull() {
            addCriterion("diseaes is null");
            return (Criteria) this;
        }

        public Criteria andDiseaesIsNotNull() {
            addCriterion("diseaes is not null");
            return (Criteria) this;
        }

        public Criteria andDiseaesEqualTo(String value) {
            addCriterion("diseaes =", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesNotEqualTo(String value) {
            addCriterion("diseaes <>", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesGreaterThan(String value) {
            addCriterion("diseaes >", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesGreaterThanOrEqualTo(String value) {
            addCriterion("diseaes >=", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesLessThan(String value) {
            addCriterion("diseaes <", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesLessThanOrEqualTo(String value) {
            addCriterion("diseaes <=", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesLike(String value) {
            addCriterion("diseaes like", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesNotLike(String value) {
            addCriterion("diseaes not like", value, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesIn(List<String> values) {
            addCriterion("diseaes in", values, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesNotIn(List<String> values) {
            addCriterion("diseaes not in", values, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesBetween(String value1, String value2) {
            addCriterion("diseaes between", value1, value2, "diseaes");
            return (Criteria) this;
        }

        public Criteria andDiseaesNotBetween(String value1, String value2) {
            addCriterion("diseaes not between", value1, value2, "diseaes");
            return (Criteria) this;
        }

        public Criteria andNumTotalIsNull() {
            addCriterion("num_total is null");
            return (Criteria) this;
        }

        public Criteria andNumTotalIsNotNull() {
            addCriterion("num_total is not null");
            return (Criteria) this;
        }

        public Criteria andNumTotalEqualTo(Integer value) {
            addCriterion("num_total =", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotEqualTo(Integer value) {
            addCriterion("num_total <>", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalGreaterThan(Integer value) {
            addCriterion("num_total >", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_total >=", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalLessThan(Integer value) {
            addCriterion("num_total <", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalLessThanOrEqualTo(Integer value) {
            addCriterion("num_total <=", value, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalIn(List<Integer> values) {
            addCriterion("num_total in", values, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotIn(List<Integer> values) {
            addCriterion("num_total not in", values, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalBetween(Integer value1, Integer value2) {
            addCriterion("num_total between", value1, value2, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("num_total not between", value1, value2, "numTotal");
            return (Criteria) this;
        }

        public Criteria andNumInfectedIsNull() {
            addCriterion("num_infected is null");
            return (Criteria) this;
        }

        public Criteria andNumInfectedIsNotNull() {
            addCriterion("num_infected is not null");
            return (Criteria) this;
        }

        public Criteria andNumInfectedEqualTo(Integer value) {
            addCriterion("num_infected =", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedNotEqualTo(Integer value) {
            addCriterion("num_infected <>", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedGreaterThan(Integer value) {
            addCriterion("num_infected >", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_infected >=", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedLessThan(Integer value) {
            addCriterion("num_infected <", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedLessThanOrEqualTo(Integer value) {
            addCriterion("num_infected <=", value, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedIn(List<Integer> values) {
            addCriterion("num_infected in", values, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedNotIn(List<Integer> values) {
            addCriterion("num_infected not in", values, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedBetween(Integer value1, Integer value2) {
            addCriterion("num_infected between", value1, value2, "numInfected");
            return (Criteria) this;
        }

        public Criteria andNumInfectedNotBetween(Integer value1, Integer value2) {
            addCriterion("num_infected not between", value1, value2, "numInfected");
            return (Criteria) this;
        }

        public Criteria andProcessingModeIsNull() {
            addCriterion("processing_mode is null");
            return (Criteria) this;
        }

        public Criteria andProcessingModeIsNotNull() {
            addCriterion("processing_mode is not null");
            return (Criteria) this;
        }

        public Criteria andProcessingModeEqualTo(String value) {
            addCriterion("processing_mode =", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeNotEqualTo(String value) {
            addCriterion("processing_mode <>", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeGreaterThan(String value) {
            addCriterion("processing_mode >", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeGreaterThanOrEqualTo(String value) {
            addCriterion("processing_mode >=", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeLessThan(String value) {
            addCriterion("processing_mode <", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeLessThanOrEqualTo(String value) {
            addCriterion("processing_mode <=", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeLike(String value) {
            addCriterion("processing_mode like", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeNotLike(String value) {
            addCriterion("processing_mode not like", value, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeIn(List<String> values) {
            addCriterion("processing_mode in", values, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeNotIn(List<String> values) {
            addCriterion("processing_mode not in", values, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeBetween(String value1, String value2) {
            addCriterion("processing_mode between", value1, value2, "processingMode");
            return (Criteria) this;
        }

        public Criteria andProcessingModeNotBetween(String value1, String value2) {
            addCriterion("processing_mode not between", value1, value2, "processingMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeIsNull() {
            addCriterion("medication_mode is null");
            return (Criteria) this;
        }

        public Criteria andMedicationModeIsNotNull() {
            addCriterion("medication_mode is not null");
            return (Criteria) this;
        }

        public Criteria andMedicationModeEqualTo(String value) {
            addCriterion("medication_mode =", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeNotEqualTo(String value) {
            addCriterion("medication_mode <>", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeGreaterThan(String value) {
            addCriterion("medication_mode >", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeGreaterThanOrEqualTo(String value) {
            addCriterion("medication_mode >=", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeLessThan(String value) {
            addCriterion("medication_mode <", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeLessThanOrEqualTo(String value) {
            addCriterion("medication_mode <=", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeLike(String value) {
            addCriterion("medication_mode like", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeNotLike(String value) {
            addCriterion("medication_mode not like", value, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeIn(List<String> values) {
            addCriterion("medication_mode in", values, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeNotIn(List<String> values) {
            addCriterion("medication_mode not in", values, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeBetween(String value1, String value2) {
            addCriterion("medication_mode between", value1, value2, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andMedicationModeNotBetween(String value1, String value2) {
            addCriterion("medication_mode not between", value1, value2, "medicationMode");
            return (Criteria) this;
        }

        public Criteria andDoseIsNull() {
            addCriterion("dose is null");
            return (Criteria) this;
        }

        public Criteria andDoseIsNotNull() {
            addCriterion("dose is not null");
            return (Criteria) this;
        }

        public Criteria andDoseEqualTo(Float value) {
            addCriterion("dose =", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseNotEqualTo(Float value) {
            addCriterion("dose <>", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseGreaterThan(Float value) {
            addCriterion("dose >", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseGreaterThanOrEqualTo(Float value) {
            addCriterion("dose >=", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseLessThan(Float value) {
            addCriterion("dose <", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseLessThanOrEqualTo(Float value) {
            addCriterion("dose <=", value, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseIn(List<Float> values) {
            addCriterion("dose in", values, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseNotIn(List<Float> values) {
            addCriterion("dose not in", values, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseBetween(Float value1, Float value2) {
            addCriterion("dose between", value1, value2, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseNotBetween(Float value1, Float value2) {
            addCriterion("dose not between", value1, value2, "dose");
            return (Criteria) this;
        }

        public Criteria andDoseUnitIsNull() {
            addCriterion("dose_unit is null");
            return (Criteria) this;
        }

        public Criteria andDoseUnitIsNotNull() {
            addCriterion("dose_unit is not null");
            return (Criteria) this;
        }

        public Criteria andDoseUnitEqualTo(String value) {
            addCriterion("dose_unit =", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitNotEqualTo(String value) {
            addCriterion("dose_unit <>", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitGreaterThan(String value) {
            addCriterion("dose_unit >", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitGreaterThanOrEqualTo(String value) {
            addCriterion("dose_unit >=", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitLessThan(String value) {
            addCriterion("dose_unit <", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitLessThanOrEqualTo(String value) {
            addCriterion("dose_unit <=", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitLike(String value) {
            addCriterion("dose_unit like", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitNotLike(String value) {
            addCriterion("dose_unit not like", value, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitIn(List<String> values) {
            addCriterion("dose_unit in", values, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitNotIn(List<String> values) {
            addCriterion("dose_unit not in", values, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitBetween(String value1, String value2) {
            addCriterion("dose_unit between", value1, value2, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andDoseUnitNotBetween(String value1, String value2) {
            addCriterion("dose_unit not between", value1, value2, "doseUnit");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountIsNull() {
            addCriterion("medication_amount is null");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountIsNotNull() {
            addCriterion("medication_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountEqualTo(Float value) {
            addCriterion("medication_amount =", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountNotEqualTo(Float value) {
            addCriterion("medication_amount <>", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountGreaterThan(Float value) {
            addCriterion("medication_amount >", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountGreaterThanOrEqualTo(Float value) {
            addCriterion("medication_amount >=", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountLessThan(Float value) {
            addCriterion("medication_amount <", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountLessThanOrEqualTo(Float value) {
            addCriterion("medication_amount <=", value, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountIn(List<Float> values) {
            addCriterion("medication_amount in", values, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountNotIn(List<Float> values) {
            addCriterion("medication_amount not in", values, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountBetween(Float value1, Float value2) {
            addCriterion("medication_amount between", value1, value2, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andMedicationAmountNotBetween(Float value1, Float value2) {
            addCriterion("medication_amount not between", value1, value2, "medicationAmount");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIsNull() {
            addCriterion("id_recorder is null");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIsNotNull() {
            addCriterion("id_recorder is not null");
            return (Criteria) this;
        }

        public Criteria andIdRecorderEqualTo(String value) {
            addCriterion("id_recorder =", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotEqualTo(String value) {
            addCriterion("id_recorder <>", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderGreaterThan(String value) {
            addCriterion("id_recorder >", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderGreaterThanOrEqualTo(String value) {
            addCriterion("id_recorder >=", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLessThan(String value) {
            addCriterion("id_recorder <", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLessThanOrEqualTo(String value) {
            addCriterion("id_recorder <=", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderLike(String value) {
            addCriterion("id_recorder like", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotLike(String value) {
            addCriterion("id_recorder not like", value, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderIn(List<String> values) {
            addCriterion("id_recorder in", values, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotIn(List<String> values) {
            addCriterion("id_recorder not in", values, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderBetween(String value1, String value2) {
            addCriterion("id_recorder between", value1, value2, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdRecorderNotBetween(String value1, String value2) {
            addCriterion("id_recorder not between", value1, value2, "idRecorder");
            return (Criteria) this;
        }

        public Criteria andIdChargeIsNull() {
            addCriterion("id_charge is null");
            return (Criteria) this;
        }

        public Criteria andIdChargeIsNotNull() {
            addCriterion("id_charge is not null");
            return (Criteria) this;
        }

        public Criteria andIdChargeEqualTo(String value) {
            addCriterion("id_charge =", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotEqualTo(String value) {
            addCriterion("id_charge <>", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeGreaterThan(String value) {
            addCriterion("id_charge >", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeGreaterThanOrEqualTo(String value) {
            addCriterion("id_charge >=", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLessThan(String value) {
            addCriterion("id_charge <", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLessThanOrEqualTo(String value) {
            addCriterion("id_charge <=", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeLike(String value) {
            addCriterion("id_charge like", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotLike(String value) {
            addCriterion("id_charge not like", value, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeIn(List<String> values) {
            addCriterion("id_charge in", values, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotIn(List<String> values) {
            addCriterion("id_charge not in", values, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeBetween(String value1, String value2) {
            addCriterion("id_charge between", value1, value2, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdChargeNotBetween(String value1, String value2) {
            addCriterion("id_charge not between", value1, value2, "idCharge");
            return (Criteria) this;
        }

        public Criteria andIdBatchIsNull() {
            addCriterion("id_batch is null");
            return (Criteria) this;
        }

        public Criteria andIdBatchIsNotNull() {
            addCriterion("id_batch is not null");
            return (Criteria) this;
        }

        public Criteria andIdBatchEqualTo(String value) {
            addCriterion("id_batch =", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchNotEqualTo(String value) {
            addCriterion("id_batch <>", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchGreaterThan(String value) {
            addCriterion("id_batch >", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchGreaterThanOrEqualTo(String value) {
            addCriterion("id_batch >=", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchLessThan(String value) {
            addCriterion("id_batch <", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchLessThanOrEqualTo(String value) {
            addCriterion("id_batch <=", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchLike(String value) {
            addCriterion("id_batch like", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchNotLike(String value) {
            addCriterion("id_batch not like", value, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchIn(List<String> values) {
            addCriterion("id_batch in", values, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchNotIn(List<String> values) {
            addCriterion("id_batch not in", values, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchBetween(String value1, String value2) {
            addCriterion("id_batch between", value1, value2, "idBatch");
            return (Criteria) this;
        }

        public Criteria andIdBatchNotBetween(String value1, String value2) {
            addCriterion("id_batch not between", value1, value2, "idBatch");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epidemic
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 23 19:52:23 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epidemic
     *
     * @mbggenerated Mon Oct 23 19:52:23 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}