package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;
import java.util.Date;

public class Fowler implements Serializable {



    private String type;

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.id
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.date_establish
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private Date dateEstablish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.address
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.num_max
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private Integer numMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.remark
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.id_recorder
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private String idRecorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fowlery.id_charge
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private String idCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.id
     *
     * @return the value of fowlery.id
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.id
     *
     * @param id the value for fowlery.id
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.date_establish
     *
     * @return the value of fowlery.date_establish
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public Date getDateEstablish() {
        return dateEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.date_establish
     *
     * @param dateEstablish the value for fowlery.date_establish
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setDateEstablish(Date dateEstablish) {
        this.dateEstablish = dateEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.address
     *
     * @return the value of fowlery.address
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.address
     *
     * @param address the value for fowlery.address
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.num_max
     *
     * @return the value of fowlery.num_max
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public Integer getNumMax() {
        return numMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.num_max
     *
     * @param numMax the value for fowlery.num_max
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setNumMax(Integer numMax) {
        this.numMax = numMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.remark
     *
     * @return the value of fowlery.remark
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.remark
     *
     * @param remark the value for fowlery.remark
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.id_recorder
     *
     * @return the value of fowlery.id_recorder
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public String getIdRecorder() {
        return idRecorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.id_recorder
     *
     * @param idRecorder the value for fowlery.id_recorder
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setIdRecorder(String idRecorder) {
        this.idRecorder = idRecorder == null ? null : idRecorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fowlery.id_charge
     *
     * @return the value of fowlery.id_charge
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public String getIdCharge() {
        return idCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fowlery.id_charge
     *
     * @param idCharge the value for fowlery.id_charge
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    public void setIdCharge(String idCharge) {
        this.idCharge = idCharge == null ? null : idCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dateEstablish=").append(dateEstablish);
        sb.append(", address=").append(address);
        sb.append(", numMax=").append(numMax);
        sb.append(", remark=").append(remark);
        sb.append(", idRecorder=").append(idRecorder);
        sb.append(", idCharge=").append(idCharge);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}