package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;
import java.util.Date;

public class Material implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id_material
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String idMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.date
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.quantity
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.unit
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.associated_firm
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String associatedFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.phone
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.remark
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id_recorder
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String idRecorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id_charge
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private String idCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table material
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id_material
     *
     * @return the value of material.id_material
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getIdMaterial() {
        return idMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id_material
     *
     * @param idMaterial the value for material.id_material
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setIdMaterial(String idMaterial) {
        this.idMaterial = idMaterial == null ? null : idMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.date
     *
     * @return the value of material.date
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.date
     *
     * @param date the value for material.date
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.quantity
     *
     * @return the value of material.quantity
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.quantity
     *
     * @param quantity the value for material.quantity
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity == null ? null : quantity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.unit
     *
     * @return the value of material.unit
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.unit
     *
     * @param unit the value for material.unit
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.associated_firm
     *
     * @return the value of material.associated_firm
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getAssociatedFirm() {
        return associatedFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.associated_firm
     *
     * @param associatedFirm the value for material.associated_firm
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setAssociatedFirm(String associatedFirm) {
        this.associatedFirm = associatedFirm == null ? null : associatedFirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.phone
     *
     * @return the value of material.phone
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.phone
     *
     * @param phone the value for material.phone
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.remark
     *
     * @return the value of material.remark
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.remark
     *
     * @param remark the value for material.remark
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id_recorder
     *
     * @return the value of material.id_recorder
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getIdRecorder() {
        return idRecorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id_recorder
     *
     * @param idRecorder the value for material.id_recorder
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setIdRecorder(String idRecorder) {
        this.idRecorder = idRecorder == null ? null : idRecorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id_charge
     *
     * @return the value of material.id_charge
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public String getIdCharge() {
        return idCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id_charge
     *
     * @param idCharge the value for material.id_charge
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    public void setIdCharge(String idCharge) {
        this.idCharge = idCharge == null ? null : idCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material
     *
     * @mbggenerated Thu Nov 16 22:57:41 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idMaterial=").append(idMaterial);
        sb.append(", date=").append(date);
        sb.append(", name=").append(name);
        sb.append(", quantity=").append(quantity);
        sb.append(", unit=").append(unit);
        sb.append(", associatedFirm=").append(associatedFirm);
        sb.append(", phone=").append(phone);
        sb.append(", remark=").append(remark);
        sb.append(", idRecorder=").append(idRecorder);
        sb.append(", idCharge=").append(idCharge);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}