package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;
import java.util.Date;

public class OutPoultry implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.quantity
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idPatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.firm
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String firm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.phone
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.id_record
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String idCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.next_process
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String nextProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_poultry
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.id
     *
     * @return the value of out_poultry.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.id
     *
     * @param id the value for out_poultry.id
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.record_date
     *
     * @return the value of out_poultry.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.record_date
     *
     * @param recordDate the value for out_poultry.record_date
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.quantity
     *
     * @return the value of out_poultry.quantity
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.quantity
     *
     * @param quantity the value for out_poultry.quantity
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.id_patch
     *
     * @return the value of out_poultry.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdPatch() {
        return idPatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.id_patch
     *
     * @param idPatch the value for out_poultry.id_patch
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdPatch(String idPatch) {
        this.idPatch = idPatch == null ? null : idPatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.firm
     *
     * @return the value of out_poultry.firm
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getFirm() {
        return firm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.firm
     *
     * @param firm the value for out_poultry.firm
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setFirm(String firm) {
        this.firm = firm == null ? null : firm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.phone
     *
     * @return the value of out_poultry.phone
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.phone
     *
     * @param phone the value for out_poultry.phone
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.remark
     *
     * @return the value of out_poultry.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.remark
     *
     * @param remark the value for out_poultry.remark
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.id_record
     *
     * @return the value of out_poultry.id_record
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdRecord() {
        return idRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.id_record
     *
     * @param idRecord the value for out_poultry.id_record
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdRecord(String idRecord) {
        this.idRecord = idRecord == null ? null : idRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.id_charge
     *
     * @return the value of out_poultry.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getIdCharge() {
        return idCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.id_charge
     *
     * @param idCharge the value for out_poultry.id_charge
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setIdCharge(String idCharge) {
        this.idCharge = idCharge == null ? null : idCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.next_process
     *
     * @return the value of out_poultry.next_process
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getNextProcess() {
        return nextProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.next_process
     *
     * @param nextProcess the value for out_poultry.next_process
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setNextProcess(String nextProcess) {
        this.nextProcess = nextProcess == null ? null : nextProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.status
     *
     * @return the value of out_poultry.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.status
     *
     * @param status the value for out_poultry.status
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_poultry
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", recordDate=").append(recordDate);
        sb.append(", quantity=").append(quantity);
        sb.append(", idPatch=").append(idPatch);
        sb.append(", firm=").append(firm);
        sb.append(", phone=").append(phone);
        sb.append(", remark=").append(remark);
        sb.append(", idRecord=").append(idRecord);
        sb.append(", idCharge=").append(idCharge);
        sb.append(", nextProcess=").append(nextProcess);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}