package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;

public class OutPoultryKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.id
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_poultry.firm
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    private String firm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table out_poultry
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.id
     *
     * @return the value of out_poultry.id
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.id
     *
     * @param id the value for out_poultry.id
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_poultry.firm
     *
     * @return the value of out_poultry.firm
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    public String getFirm() {
        return firm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_poultry.firm
     *
     * @param firm the value for out_poultry.firm
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    public void setFirm(String firm) {
        this.firm = firm == null ? null : firm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_poultry
     *
     * @mbggenerated Sat Jan 13 18:33:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", firm=").append(firm);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}