package cn.zhku.waterfowl.pojo.entity;

import java.io.Serializable;

public class Transportation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.id
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.id_patch
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String idPatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.method
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.firm
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String firm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.site
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.customer
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.c_phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.address
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transportation.quantity
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transportation
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.id
     *
     * @return the value of transportation.id
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.id
     *
     * @param id the value for transportation.id
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.id_patch
     *
     * @return the value of transportation.id_patch
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getIdPatch() {
        return idPatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.id_patch
     *
     * @param idPatch the value for transportation.id_patch
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setIdPatch(String idPatch) {
        this.idPatch = idPatch == null ? null : idPatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.method
     *
     * @return the value of transportation.method
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.method
     *
     * @param method the value for transportation.method
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.firm
     *
     * @return the value of transportation.firm
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getFirm() {
        return firm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.firm
     *
     * @param firm the value for transportation.firm
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setFirm(String firm) {
        this.firm = firm == null ? null : firm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.site
     *
     * @return the value of transportation.site
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.site
     *
     * @param site the value for transportation.site
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.phone
     *
     * @return the value of transportation.phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.phone
     *
     * @param phone the value for transportation.phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.customer
     *
     * @return the value of transportation.customer
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.customer
     *
     * @param customer the value for transportation.customer
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.c_phone
     *
     * @return the value of transportation.c_phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.c_phone
     *
     * @param cPhone the value for transportation.c_phone
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.address
     *
     * @return the value of transportation.address
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.address
     *
     * @param address the value for transportation.address
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transportation.quantity
     *
     * @return the value of transportation.quantity
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transportation.quantity
     *
     * @param quantity the value for transportation.quantity
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Mon Jan 22 13:26:24 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idPatch=").append(idPatch);
        sb.append(", method=").append(method);
        sb.append(", firm=").append(firm);
        sb.append(", site=").append(site);
        sb.append(", phone=").append(phone);
        sb.append(", customer=").append(customer);
        sb.append(", cPhone=").append(cPhone);
        sb.append(", address=").append(address);
        sb.append(", quantity=").append(quantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}