package cn.zhku.waterfowl.pojo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransportationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public TransportationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(String value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(String value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(String value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(String value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(String value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(String value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLike(String value) {
            addCriterion("cid like", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotLike(String value) {
            addCriterion("cid not like", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<String> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<String> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(String value1, String value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(String value1, String value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(String value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(String value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(String value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(String value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(String value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(String value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLike(String value) {
            addCriterion("tid like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotLike(String value) {
            addCriterion("tid not like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<String> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<String> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(String value1, String value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(String value1, String value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andIdPatchIsNull() {
            addCriterion("id_patch is null");
            return (Criteria) this;
        }

        public Criteria andIdPatchIsNotNull() {
            addCriterion("id_patch is not null");
            return (Criteria) this;
        }

        public Criteria andIdPatchEqualTo(String value) {
            addCriterion("id_patch =", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotEqualTo(String value) {
            addCriterion("id_patch <>", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchGreaterThan(String value) {
            addCriterion("id_patch >", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchGreaterThanOrEqualTo(String value) {
            addCriterion("id_patch >=", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLessThan(String value) {
            addCriterion("id_patch <", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLessThanOrEqualTo(String value) {
            addCriterion("id_patch <=", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchLike(String value) {
            addCriterion("id_patch like", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotLike(String value) {
            addCriterion("id_patch not like", value, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchIn(List<String> values) {
            addCriterion("id_patch in", values, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotIn(List<String> values) {
            addCriterion("id_patch not in", values, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchBetween(String value1, String value2) {
            addCriterion("id_patch between", value1, value2, "idPatch");
            return (Criteria) this;
        }

        public Criteria andIdPatchNotBetween(String value1, String value2) {
            addCriterion("id_patch not between", value1, value2, "idPatch");
            return (Criteria) this;
        }

        public Criteria andCurquantityIsNull() {
            addCriterion("curQuantity is null");
            return (Criteria) this;
        }

        public Criteria andCurquantityIsNotNull() {
            addCriterion("curQuantity is not null");
            return (Criteria) this;
        }

        public Criteria andCurquantityEqualTo(Float value) {
            addCriterion("curQuantity =", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityNotEqualTo(Float value) {
            addCriterion("curQuantity <>", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityGreaterThan(Float value) {
            addCriterion("curQuantity >", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityGreaterThanOrEqualTo(Float value) {
            addCriterion("curQuantity >=", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityLessThan(Float value) {
            addCriterion("curQuantity <", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityLessThanOrEqualTo(Float value) {
            addCriterion("curQuantity <=", value, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityIn(List<Float> values) {
            addCriterion("curQuantity in", values, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityNotIn(List<Float> values) {
            addCriterion("curQuantity not in", values, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityBetween(Float value1, Float value2) {
            addCriterion("curQuantity between", value1, value2, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurquantityNotBetween(Float value1, Float value2) {
            addCriterion("curQuantity not between", value1, value2, "curquantity");
            return (Criteria) this;
        }

        public Criteria andCurlngIsNull() {
            addCriterion("curLng is null");
            return (Criteria) this;
        }

        public Criteria andCurlngIsNotNull() {
            addCriterion("curLng is not null");
            return (Criteria) this;
        }

        public Criteria andCurlngEqualTo(Float value) {
            addCriterion("curLng =", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngNotEqualTo(Float value) {
            addCriterion("curLng <>", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngGreaterThan(Float value) {
            addCriterion("curLng >", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngGreaterThanOrEqualTo(Float value) {
            addCriterion("curLng >=", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngLessThan(Float value) {
            addCriterion("curLng <", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngLessThanOrEqualTo(Float value) {
            addCriterion("curLng <=", value, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngIn(List<Float> values) {
            addCriterion("curLng in", values, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngNotIn(List<Float> values) {
            addCriterion("curLng not in", values, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngBetween(Float value1, Float value2) {
            addCriterion("curLng between", value1, value2, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlngNotBetween(Float value1, Float value2) {
            addCriterion("curLng not between", value1, value2, "curlng");
            return (Criteria) this;
        }

        public Criteria andCurlatIsNull() {
            addCriterion("curLat is null");
            return (Criteria) this;
        }

        public Criteria andCurlatIsNotNull() {
            addCriterion("curLat is not null");
            return (Criteria) this;
        }

        public Criteria andCurlatEqualTo(Float value) {
            addCriterion("curLat =", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatNotEqualTo(Float value) {
            addCriterion("curLat <>", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatGreaterThan(Float value) {
            addCriterion("curLat >", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatGreaterThanOrEqualTo(Float value) {
            addCriterion("curLat >=", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatLessThan(Float value) {
            addCriterion("curLat <", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatLessThanOrEqualTo(Float value) {
            addCriterion("curLat <=", value, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatIn(List<Float> values) {
            addCriterion("curLat in", values, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatNotIn(List<Float> values) {
            addCriterion("curLat not in", values, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatBetween(Float value1, Float value2) {
            addCriterion("curLat between", value1, value2, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurlatNotBetween(Float value1, Float value2) {
            addCriterion("curLat not between", value1, value2, "curlat");
            return (Criteria) this;
        }

        public Criteria andCurdateIsNull() {
            addCriterion("curDate is null");
            return (Criteria) this;
        }

        public Criteria andCurdateIsNotNull() {
            addCriterion("curDate is not null");
            return (Criteria) this;
        }

        public Criteria andCurdateEqualTo(Date value) {
            addCriterion("curDate =", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateNotEqualTo(Date value) {
            addCriterion("curDate <>", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateGreaterThan(Date value) {
            addCriterion("curDate >", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateGreaterThanOrEqualTo(Date value) {
            addCriterion("curDate >=", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateLessThan(Date value) {
            addCriterion("curDate <", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateLessThanOrEqualTo(Date value) {
            addCriterion("curDate <=", value, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateIn(List<Date> values) {
            addCriterion("curDate in", values, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateNotIn(List<Date> values) {
            addCriterion("curDate not in", values, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateBetween(Date value1, Date value2) {
            addCriterion("curDate between", value1, value2, "curdate");
            return (Criteria) this;
        }

        public Criteria andCurdateNotBetween(Date value1, Date value2) {
            addCriterion("curDate not between", value1, value2, "curdate");
            return (Criteria) this;
        }

        public Criteria andDriverIsNull() {
            addCriterion("driver is null");
            return (Criteria) this;
        }

        public Criteria andDriverIsNotNull() {
            addCriterion("driver is not null");
            return (Criteria) this;
        }

        public Criteria andDriverEqualTo(String value) {
            addCriterion("driver =", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotEqualTo(String value) {
            addCriterion("driver <>", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThan(String value) {
            addCriterion("driver >", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThanOrEqualTo(String value) {
            addCriterion("driver >=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThan(String value) {
            addCriterion("driver <", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThanOrEqualTo(String value) {
            addCriterion("driver <=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLike(String value) {
            addCriterion("driver like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotLike(String value) {
            addCriterion("driver not like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverIn(List<String> values) {
            addCriterion("driver in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotIn(List<String> values) {
            addCriterion("driver not in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverBetween(String value1, String value2) {
            addCriterion("driver between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotBetween(String value1, String value2) {
            addCriterion("driver not between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transportation
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 04 21:51:04 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table transportation
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}