package cn.zhku.waterfowl.pojo.mapper;

import cn.zhku.waterfowl.pojo.entity.AquaStor;
import cn.zhku.waterfowl.pojo.entity.AquaStorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AquaStorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int countByExample(AquaStorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int deleteByExample(AquaStorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int insert(AquaStor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int insertSelective(AquaStor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    List<AquaStor> selectByExample(AquaStorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") AquaStor record, @Param("example") AquaStorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqua_stor
     *
     * @mbggenerated Tue Jan 16 13:09:27 CST 2018
     */
    int updateByExample(@Param("record") AquaStor record, @Param("example") AquaStorExample example);
}