package cn.zhku.waterfowl.pojo.mapper;

import cn.zhku.waterfowl.pojo.entity.Fowlery;
import cn.zhku.waterfowl.pojo.entity.FowleryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FowleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int countByExample(FowleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int deleteByExample(FowleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int insert(Fowlery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int insertSelective(Fowlery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    List<Fowlery> selectByExample(FowleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    Fowlery selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") Fowlery record, @Param("example") FowleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int updateByExample(@Param("record") Fowlery record, @Param("example") FowleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int updateByPrimaryKeySelective(Fowlery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fowlery
     *
     * @mbggenerated Thu Oct 26 20:43:45 CST 2017
     */
    int updateByPrimaryKey(Fowlery record);

    /**
     * 通过类型查找禽舍的id
     * @param type
     * @return  禽舍的id
     */
    List<String> findFowleryIdByType(String type);

    /**
     * 通过id查找禽舍的可存放最大数
     * @param id
     * @return 数量
     */
    Integer findMaxNumById(String id);

    /**
     * 通过id查找已经别存放的数量
     * @param id
     * @return  已经被存放是数量
     */
    Integer findUsedNumById(String id);
}