package cn.zhku.waterfowl.pojo.mapper;

import cn.zhku.waterfowl.pojo.entity.Transcompany;
import cn.zhku.waterfowl.pojo.entity.TranscompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TranscompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int countByExample(TranscompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int deleteByExample(TranscompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int insert(Transcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int insertSelective(Transcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    List<Transcompany> selectByExample(TranscompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    Transcompany selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") Transcompany record, @Param("example") TranscompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int updateByExample(@Param("record") Transcompany record, @Param("example") TranscompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int updateByPrimaryKeySelective(Transcompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transcompany
     *
     * @mbggenerated Sun Feb 04 21:51:04 CST 2018
     */
    int updateByPrimaryKey(Transcompany record);
}